### ISSUE TITLE
Figure out the deal with the barometric pressure data ...

### ISSUE THREAD

**Issue by seanmcm** [djkelly00/soil_probe#6]

**Comment by jess-shue** [comment]
@seanmcm @djkelly00 The details of the barometric pressure variables downloaded from the NEON site are contained in a file named:  NEON.D02.SERC.DP1.00004.001.**variables**.20200621T113753Z.csv that varies based on the name of the data files. I think the key variables for us are:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



fieldName | description | dataType | units
-- | -- | -- | --
startDateTime | Date and time at which a sampling is initiated | dateTime | NA
endDateTime | Date and time at which a sampling is completed | dateTime | NA
staPresMean | Arithmetic mean of station pressure | real | kilopascal
corPres | Mean station pressure corrected to sea level | real | kilopascal



</body>

</html>
